window.languages =
{
  "en":{
    "menuList":[

    ],
    "language":"Language",
    "aboutheader":"About Us",
    "about":"Copyright @ 2012 Department of Psychology - The University of Hong Kong. All rights reserved.",
    "disclaimer_0":"Important Notice",
    "disclaimer_0_description":"The information provided by the proACT App is not intended to provide a diagnosis or to provide treatment to a given patient, but to aid face-to-face psychological treatment provided by professional and trained psychotherapists. Users are necessary to bare their own risk. No personal information is obtained by proACT.",
    "disclaimer_1":"Disclaimer",
    "disclaimer_1_description":"By using this App, you signify your assent to these Terms and Conditions. If you do not agree to all of these Terms and Conditions of use, please do not use this App.",
    "disclaimer_11_description":"Last Updated: November 18, 2013",
    "disclaimer_111_description":"2012 Department of Psychology, The University of Hong Kong. All rights reserved.",
    "disclaimer_2":"Medical Disclaimer",
    "disclaimer_2_description":"You understand and agree that any information obtained through proACT App may be used for research purposes, and is not to be relied upon for the proper diagnosis, care and treatment of a patient. Any information you receive through the proACT App is not a substitute for your competent medical advice and professional judgment. We encourage you to confirm information obtained through the proACT App with reliable sources before relying upon such information.",
    "disclaimer_4":"Liability of proACT App and Its Licensors",
    "disclaimer_4_description":"You acknowledge and agree that you assume full responsibility for your use of the proACT App and that proACT App licensors, suppliers, or any third parties mentioned on the proACT App are not responsible for or liable for any claim, loss or damage arising from your use of the proACT App.",
    "disclaimer_5":"Cancellation of Service",
    "disclaimer_5_description":"You agree that we may cancel our service at any time, for any reason, without warning or compensation.",
    "disclaimer_6":"Amendments",
    "disclaimer_6_description":"We may amend this Agreement from time to time. After amending the Agreement, we may, but are not obligated to, notify you of the changes and request your acceptance of them. ",
    "disclaimer_61_description":"Your continued use of our service, whether we have notified you or not, means that you accept our Amendments. We recommend that you review our Terms of Service each time that you visit proACT App.",
    "disclaimer_62_description":"You may refuse to agree to the Amendments, but if you do, you must stop using our service immediately.",
    "disclaimer_8":"Emergency",
    "disclaimer_8_description":"Since your therapist cannot guarantee that they read your submitted records regularly; hence in case of emergency, please dial the following numbers:",
    "disclaimer_81_description":"Hong Kong Police Force - Tel: 999 (24-hour hotline)",
    "disclaimer_82_description":"Caritas Family Crisis Support Hotline - Tel: 18288 (24-hour hotline)",
    "disclaimer_83_description":"Suicide Prevention Service Hotline - Tel: 23820000 (24-hour hotline)",
    "disclaimer_84_description":"The Samaritan Befrienders Hong Kong Hotline - Tel: 23892222 (24-hour hotline)",
    "disclaimer_85_description":"TWGHs CEASE Crisis Centre Hotline - Tel: 18281 (24-hour hotline)",
    "disclaimer_86_description":"The Mental Health Association of Hong Kong Hotline - Tel: 27720047",
    "disclaimer_87_description":"Hospital Authority Mental Health Hotline - Tel: 24667350",
    "disclaimer_7":"If there is any inconsistency or conflict between English and Chinese version, the English version shall prevail. In case of disputes, the decision of Department of Psychology, University of Hong Kong shall be final.",
    "menu":"Menu",
    "guide":"Guide",
    "menu_askLogin":"Please login!",
    "email":"Email:",
    "password":"Password:",
    "newPassword":"New password:",
    "fname":"First name:",
    "lname":"Last name:",
    "initial":"Initials:",
    "refNo":"6-digit reference code: (Please leave blank if you don't have a therapist)",
    "therapistlast":"Last name of therapist:",
    "login":"Login",
    "logout":"Logout",
    "logoutError":"Logout failure!",
    "loginError":"Incorrect email or password!",
    "logoutSuccessful":"Logout successful!",
    "registration":"Registration",
    "forget":"Forget Password",
    "register":"Register",
    "registrationError":"Email already registered!",
    "registrationError1":"No such code!",
    "registrationError2":"This therapist did not registered for using the system!",
    "registrationCodeError":"Registration code does not match with last name!",
    "registrationFail":"Registration failed! Please check Internet connection.",
    "registrationFailF":"Registration Failed!",
    "registrationError_incorrectEmail":"Email format incorrect!",
    "registrationsSuccessful":"Registration successful!",
    "userInfo":"User information",
    "userPassword":"Update password",
    "userInfo_update":"update",
    "userInfo_updateError":"Update failure!",
    "userInfo_updateSuccessful":"Update successful!",
    "userPassword_updateSuccessful":"Update successful, please login again!",
    "back":"Back",
    "next":"Next",
    "dtr_situationText":"Situation that leads you to the unpleasant emotion:",
    "dtr_initialThoughtText":"Your initial thought:",
    "dtr_SummaryBelieveText":"The changes on your belief:",
    "dtr_BelieveText":"Thought goes through your mind:",
    "dtr_distortionText":"Your Thought Distortions:",
    "dtr_modifiedThoughtText":"Your Adaptive Response:",
    "dtr_botheredSituation":"What actual event or stream of thoughts, or daydreams or recollection led to the unpleasant emotion?",
    "dtr_table_initialThought":"Initial Feeling",
    "dtr_table_modifiedThought":"Modified Feeling",
    "dtr_table_feeling":"Feelings",
    "dtr_table_believe":"Belief",
    "dtr_table_initialBelieve":"Initial Belief",
    "dtr_table_modifiedBelieve":"Modified Belief",
    "dtr_thought":"What was your interpretation of the event? What thoughts passed through your mind?",
    "dtr_emotion":"What emotion(s) do you feel now and how intense (0-100%) is the emotion?",
    "dtr_anotherSituation":"Use questions at the bottom to compose a response to the automatic thought.",
    "dtr_page1":"Event & Thought",
    "dtr_page1_feelBar":"How strongly did you feel in this way (0-100%)?",
    "dtr_page1_feelBar_add":"Press to add more emotions...",
    "dtr_page2_feelBar":"Which distortions can you identify in your thought?",
    "dtr_page3_feelBar":"How intense is the emotion do you feel now? (0-100%)",
    "dtr_page2_believeBar":"How much did you believe this thought at the time? (0-100%)",
    "dtr_page3_believeBar":"How much do you now believe the automatic thought? (0-100%)",
    "dtr_page2":"Automatic Thought",
    "dtr_page3":"Adaptive Response",
    "dtr_page4":"Summary",
    "dtr_page5":"Thought Distortions",
    "dtr_feel":[
      "Angry",
      "Annoyed",
      "Anxious",
      "Ashamed",
      "Bored",
      "Confused",
      "Dejected",
      "Depressed",
      "Demoralized",
      "Disappointed",
      "Disgusted",
      "Embarrassed",
      "Envious",
      "Frightened",
      "Frustrated",
      "Guilty",
      "Humiliated",
      "Hurt",
      "Insecure",
      "Irritated",
      "Jealous",
      "Lonely",
      "Nervous",
      "Panicky",
      "Resentful",
      "Sad",
      "Scared",
      "Self-conscious",
      "Stressed",
      "Worried"
    ],
    "dtr_distortion":[
      {
        "name":"All-or-Nothing Thinking",
        "description":"You look at things in absolute, black and white categories. If your performance falls short of perfect, you see yourself as a total failure."
      },
      {
        "name":"Overgeneralization",
        "description":"You view a negative event as a never-ending pattern of defeat."
      },
      {
        "name":"Mental Filter",
        "description":"You pick out a single negative detail and dwell on it exclusively so that your vision of all reality becomes darkened, like the drop of ink that discolors of the entire beaker of water."
      },
      {
        "name":"Disqualifying The Positive",
        "description":"You reject positive experiences by insisting they 'don't count' for some reason or other. In this way you can maintain a negative belief that is contradicted by your everyday experiences."
      },
      {
        "name":"Jumping To Conclusions",
        "description":"You make a negative interpretation even though there are no definite facts that convincingly support your conclusions. a. Mind Reading: You arbitrarily conclude that someone is reacting negatively to you, and you don't bother to check this out. b. The Fortune Teller Error: You anticipate that things will turn out badly, and you feel convinced that your prediction is an already established fact."
      },
      {
        "name":"Magnification (Catastrophizing) Or Minimization",
        "description":"You exaggerate the importance of things (such as your goof-up or someone else's achievement). Or you inappropriately shrink things until they appear tiny (your own desirable qualities or the other fellow's imperfections)."
      },
      {
        "name":"Emotional Reasoning",
        "description":"You assume that your negative emotions necessarily reflect the way things really are: 'I feel it, therefore it must be true.'"
      },
      {
        "name":"Should Statements",
        "description":"You try to motivate yourself with shoulds and shouldn's, as if you had to be whipped and punished before you could be expected to do anything. 'Musts' and 'oughts' are also offenders. The emotional consequence is guilt. When you direct should statements toward others, you feel anger, frustration, and resentment."
      },
      {
        "name":"Labeling and Mislabeling",
        "description":"This is an extreme form of over-generalization. Instead of describing your error, you attach a negative label to yourself: 'I'm a loser.' When someone else’s behavior rubs you the wrong way, you attach a negative label to him: “He’s a damn louse.” Mislabeling involves describing an event with language that is highly colored and emotionally loaded."
      },
      {
        "name":"Personalization",
        "description":"You see yourself as the cause of some negative event which in fact you were not primarily responsible for."
      }
    ],
    "dtr_reference":"Reference: Burns, D. D. (1999). The Feeling Good Handbook. Plume.",
    "list":"Distortion List Guide",
    "dtr_page6":"Outcome",
    "dtr_anotherFeeling":"What is another way to think about this situation (without distortions)?",
    "dtr_alternativeresponse":"Use questions to help composing an alternative response:",
    "dtr_question_one":"Question 1:",
    "dtr_question_one_step":"What is the evidence that the automatic thought is true? Not true?",
    "dtr_question_two":"Question 2:",
    "dtr_question_two_step":"Is there an alternative explanation?",
    "dtr_question_three":"Question 3:",
    "dtr_question_three_step":"What's the worst that could happen? Could I live through it? What's the best that could happen? What's the most realistic outcome?",
    "dtr_question_four":"Question 4:",
    "dtr_question_four_step":"What's the effect of believing the automatic thought? What could be the effect of changing my thinking?",
    "dtr_question_five":"Question 5:",
    "dtr_question_five_step":"What should I do about it?",
    "dtr_question_six":"Question 6:",
    "dtr_question_six_step":"If my friend was in the situation and had this thought, what would I tell him / her?",
    "dtrMenuList":[

    ],
    "dtr_resultBelieve":"Changes on Belief:",
    "dtr_resultFeeling":"Result",
    "btnSetting":"Setting",
    "dtr_btnRecordJournal":"Save Journal",
    "dtr_btnEmail":"Email Journal",
    "dtr_btnDelete":"Delete",
    "dtr_btn_email":"Send",
    "dtr_emailSending":"Sending...",
    "dtr_btn_myEmail":"Receiver's email address",
    "dtr_emailJournalFailure":"Failure!",
    "dtr_emailJournalSuccessful":"Successful!",
    "dtr_error_noReceiver":"Please input receiver's email address",
    "dtr_recordJournalFailure":"Record failure! Reason: Incomplete submission. Please check your Internet connection and fill in all the required field.",
    "dtr_deleteJournalFailure":"Delete Failure! ",
    "dtr_deleteJournalSuccessful":"Delete Successful!",
    "dtr_recordJournalSuccessful":"Record Successful!",
    "dtr_confirmDeleteRecord":"Delete?",
    "dtr_emailReceiver":"Receiver:",
    "dtr_header_recordList":"Thought History",
    "therapist":"Therapist:",
    "dtrlist_header_guide":"Distortion List",
    "dtr_guide_step0_name":"All-or-Nothing Thinking",
    "dtr_guide_step0_description":"You look at things in absolute, black and white categories. If your performance falls short of perfect, you see yourself as a total failure.",
    "dtr_guide_step1_name":"Overgeneralization",
    "dtr_guide_step1_description":"You view a negative event as a never-ending pattern of defeat.",
    "dtr_guide_step2_name":"Mental Filter",
    "dtr_guide_step2_description":"You pick out a single negative detail and dwell on it exclusively so that your vision of all reality becomes darkened, like the drop of ink that discolors of the entire beaker of water.",
    "dtr_guide_step3_name":"Disqualifying The Positive",
    "dtr_guide_step3_description":"You reject positive experiences by insisting they 'don't count' for some reason or other. In this way you can maintain a negative belief that is contradicted by your everyday experiences.",
    "dtr_guide_step4_name":"Jumping To Conclusions",
    "dtr_guide_step4_description":"You make a negative interpretation even though there are no definite facts that convincingly support your conclusions. a. Mind Reading: You arbitrarily conclude that someone is reacting negatively to you, and you don't bother to check this out. b. The Fortune Teller Error: You anticipate that things will turn out badly, and you feel convinced that your prediction is an already established fact.",
    "dtr_guide_step5_name":"Magnification Or Minimization",
    "dtr_guide_step5_description":"You exaggerate the importance of things (such as your goof-up or someone else's achievement). Or you inappropriately shrink things until they appear tiny (your own desirable qualities or the other fellow's imperfections).",
    "dtr_guide_step6_name":"Emotional Reasoning",
    "dtr_guide_step6_description":"You assume that your negative emotions necessarily reflect the way things really are: 'I feel it, therefore it must be true.'",
    "dtr_guide_step7_name":"Should Statements",
    "dtr_guide_step7_description":"You try to motivate yourself with shoulds and shouldn's, as if you had to be whipped and punished before you could be expected to do anything. 'Musts' and 'oughts' are also offenders. The emotional consequence is guilt. When you direct should statements toward others, you feel anger, frustration, and resentment.",
    "dtr_guide_step8_name":"Labeling and Mislabeling",
    "dtr_guide_step8_description":"This is an extreme form of over-generalization. Instead of describing your error, you attach a negative label to yourself: 'I'm a loser.' When someone else’s behavior rubs you the wrong way, you attach a negative label to him: “He’s a damn louse.” Mislabeling involves describing an event with language that is highly colored and emotionally loaded.",
    "dtr_guide_step9_name":"Personalization",
    "dtr_guide_step9_description":"You see yourself as the cause of some negative event which in fact you were not primarily responsible for.",
    "dtr_guide0_name":"All-or-Nothing Thinking",
    "dtr_guide1_name":"Overgeneralization",
    "dtr_guide2_name":"Mental Filter",
    "dtr_guide3_name":"Disqualifying The Positive",
    "dtr_guide4_name":"Jumping To Conclusions",
    "dtr_guide5_name":"Magnification (Catastrophizing) Or Minimization",
    "dtr_guide6_name":"Emotional Reasoning",
    "dtr_guide7_name":"Should Statements",
    "dtr_guide8_name":"Labeling and Mislabeling",
    "dtr_guide9_name":"Personalization",
    "baMenuList":[

    ],
    "mcMenuList":[

    ],
    "mc_header_page1":"Mood Chart",
    "mc_btn_add":"Save Record",
    "mc_lbl_anxious":"How anxious do you feel now? (0-100%)",
    "mc_lbl_depressed":"How depressed do you feel now? (0-100%)",
    "mc_lbl_stress":"How stressful do you feel now? (0-100%)",
    "mc_header_recordList":"Past Mood Charts",
    "mc_lbl_submitDate":"Submit Date:",
    "mc_deleteSuccessful":"Delete Successful!",
    "mc_recordSuccessful":"Record Successful!",
    "mc_deleteFailure":"Delete Failure!",
    "mc_confirmDeleteRecord":"Delete?",
    "ba_lbl_content":"What activities have you completed?",
    "ba_lbl_anxious":"How anxious do you feel now? (0-100%)",
    "ba_lbl_depressed":"How depressed do you feel now? (0-100%)",
    "ba_lbl_stress":"How stressful do you feel now? (0-100%)",
    "ba_lbl_date":"Date:",
    "ba_lbl_time":"Time:",
    "ba_lbl_userInputDate":"Date:",
    "ba_lbl_submitDate":"Submit Date:",
    "plan_header":"Plan Activity",
    "plan_activity":"What activities are you planning?",
    "plan_time":"When are you going to do it?",
    "plan_lbl_date":"Date:",
    "plan_lbl_time":"Time:",
    "plan_btn_add":"Save Plan",
    "plan_recordFailure":"Record Failure! Please check your Internet connection.",
    "plan_deleteFailure":"Delete Failure!",
    "plan_deleteSuccessful":"Delete Successful!",
    "plan_recordSuccessful":"Record Successful!",
    "plan_confirmDeleteRecord":"Delete?",
    "plan_menu_baReminder":"proACT Notification",
    "plan_baReminder_notSupport":"plan_baReminder_notSupport eng",
    "plan_baReminder_ticker":"proACT Behavioral Activation Activity Reminder",
    "plan_baReminder_title":"proACT Behavioral Activation Activity Reminder",
    "plan_baReminder_msg":"You have planned to do one of the activities now!",
    "plan_header_recordList":"Created Plan",
    "plan_lbl_userInputDate":"Date:",
    "plan_lbl_submitDate":"Submit Date:",
    "plan_lbl_activity":"Planned Activity:",
    "ba_btn_add":"Save Record",
    "ba_header_page1":"Practice",
    "ba_header_page2":"Plan",
    "ba_recordFailure":"Record failure! Reason: Incomplete submission. Please check your Internet connection and fill in all the required fields.",
    "ba_deleteFailure":"Delete Failure!",
    "ba_deleteSuccessful":"Delete Successful!",
    "ba_recordSuccessful":"Record Successful!",
    "login_lbl_autoLogin":"Auto Login",
    "ba_confirmDeleteRecord":"Delete?",
    "ba_header_recordList":"Practice Record",
    "ba_header_recordList2":"Created Plans",
    "ba_menu_baReminder":"proACT Notification",
    "ba_baReminder_notSupport":"ba_baReminder_notSupport eng",
    "ba_baReminder_ticker":"proACT Behavioral Activation Reminder",
    "ba_baReminder_title":"proACT Behavioral Activation Reminder",
    "ba_baReminder_msg":"It's time to fill in the behavioral activation form!",
    "be_lbl_length":"Length of Exercise (mins):",
    "be_lbl_script":"Script:",
    "be_reocrd_lbl_scriptName":"Script name:",
    "be_reocrd_btn_start":"Start",
    "be_reocrd_btn_stop":"Stop",
    "be_reocrd_msg_pleaseInputName":"Please input name.",
    "be_reocrd_msg_pleaseInputLength":"Please input length.",
    "be_reocrd_msg_pleaseRecord":"Please record first.",
    "be_reocrd_msg_playRecordError":"File cannot be found.",
    "be_reocrd_msg_pleaseStopPlaying":"Please stop the current playing audio.",
    "be_reocrd_msg_deleteError":"Please ensure the audio file is stored and has stopped playing!",
    "be_reocrd_msg_deleteConfirmation":"Delete?",
    "be_reocrd_msg_deleteSuccessful":"Deleted",
    "be_reocrd_msg_deleteFailure":"Delete failed",
    "be_reocrd_msg_recordFailure":"Your device cannot record.",
    "be_reocrd_btn_play":"Play",
    "be_reocrd_btn_pause":"Pause",
    "be_reocrd_btn_delete":"Delete",
    "be_index_btn_record":"Record",
    "be_index_btn_delete":"Delete",
    "be_index_btn_guide":"Guide",
    "be_index_noScript":"No script is selected",
    "be_header_index":"Behaviorial Exercise",
    "be_header_guide":"Instruction Guide",
    "be_header_record":"Record Script",
    "be_header_delete":"Delete",
    "be_recordFailure":"Record failure! Please check your Internet connection.",
    "be_recordSuccessful":"Record Successful!",
    "sdMenuList":[

    ],
    "sd_header_index":"Sleep Diary",
    "sd_lbl_date":"Date:",
    "sd_goToBed_time":"What time did you get into bed?",
    "sd_trySleep_time":"What time did you try to go to sleep?",
    "sd_fallSleep_time":"How long did it take you to fall asleep?",
    "sd_fallSleep_time_hour":"Hour:",
    "sd_fallSleep_time_min":"Minute:",
    "sd_totalAwake_time":"What was the total time you were awake during sleep?",
    "sd_totalAwake_hour":"Hour:",
    "sd_totalAwake_min":"Minute:",
    "sd_getOutBed_time":"What time did you get out of bed for the day?",
    "sd_totalSleep_time":"How long did you sleep?",
    "sd_totalSleep_hour":"Hour:",
    "sd_totalSleep_min":"Minute:",
    "sd_sleepQuality":"Rate your quality of sleep:",
    "sd_verygood_sq":"Very Good",
    "sd_good_sq":"Relatively Good",
    "sd_poor_sq":"Relatively Poor",
    "sd_verypoor_sq":"Very Poor",
    "sd_sleepEfficiency":"How rested or refreshed did you feel when you woke up for the day?",
    "sd_verywell_se":"Very well-rested",
    "sd_well_se":"Well-rested",
    "sd_somewhat_se":"Somewhat rested",
    "sd_slightly_se":"Slightly rested",
    "sd_notatall_se":"Not at all rested",
    "sd_totalNap_time":"How long did you nap or doze yesterday?",
    "sd_totalNap_hour":"Hour:",
    "sd_totalNap_min":"Minute:",
    "sd_alcohol":"Alcohol: (drink*)",
    "sd_alcoholTxt":"* 1 drink = one standard  beer (can), 100ml red wine, or 25ml liquor.",
    "sd_caffeine":"Caffeine: ( cup of coffee / tea / soda / coke )",
    "sd_medicine":"Hypnotics: (over-the-counter / prescription medications)",
    "sd_medication_yesTxt":"Yes",
    "sd_medication_noTxt":"No",
    "sd_medication_name":"Name of Medicine:",
    "sd_medication_dose":"Dosage:",
    "sd_btn_add":"Save Diary",
    "sd_recordSuccessful":"Record Successful!",
    "sd_recordFailure":"Record failure! Reason: Incomplete submission or wrong input of the 'total sleep time' (i.e. the total sleep time is longer than the total time in bed).",
    "sd_deleteSuccessful":"Delete Successful!",
    "sd_deleteFailure":"Delete Failure!",
    "sd_confirmDeleteRecord":"Delete?",
    "sd_header_guide":"Sleep Diary Guide",
    "sd_guide_title":"Frequently Asked Questions / Instructions",
    "sd_guide_step":[
      {
        "name":"1. What time did you get into bed?",
        "description":""
      },
      {
        "name":"2. What time did you try to go to sleep?",
        "description":"This may not be the time you get into bed. (For example: You get into bed at 11:00p.m., and try to sleep at 11:30p.m. after 30-min of reading.)"
      },
      {
        "name":"3. How long did it take you to fall asleep?",
        "description":""
      },
      {
        "name":"4. What was the total time you were awake during sleep?",
        "description":"For example: You were awake 3 times, and 20 min each. (3 X 20 min = 1 hr)"
      },
      {
        "name":"5. What time did you get out of bed for the day?",
        "description":"What time did you get out of bed with no further attempt at sleeping? (For example: You wake up at 8:00a.m., and get out of bed at 9:00a.m.)"
      },
      {
        "name":"6. How long did you sleep?",
        "description":"This should just be your best estimate"
      },
      {
        "name":"7. Rate your quality of sleep",
        "description":""
      },
      {
        "name":"8. How rested or refreshed did you feel when you woke up for the day",
        "description":"This refers to how you felt after you were done sleeping for the night, during the first few minutes that you were awake."
      },
      {
        "name":"9. How long did you nap or doze yesterday?",
        "description":"Duration of nap and doze between the time you get out of bed in the morning and get into bed at night."
      },
      {
        "name":"10. Alcohol: (drink*)",
        "description":"* 1 drink = one standard  beer (can), 100ml red wine, or 25ml liquor."
      },
      {
        "name":"11. Caffeine: ( cup of coffee / tea / soda / coke )",
        "description":" 1 cup = one normal hot drink size in Cantonese-style restaurant "
      },
      {
        "name":"12. Hypnotics: (over-the-counter / prescription medications)",
        "description":"Include medication available over the counter, prescription medications, and herbals (with hypnotics effects)"
      }
    ],
    "sd_header_recordList":"Past Sleep Diary",
    "sd_lbl_userInputDate":"Date:",
    "sd_lbl_submitDate":"Submitted Date:",
    "sd_lbl_inbedtime":"What time did you get into bed?",
    "sd_lbl_trysleeptime":"What time did you try to go to sleep?",
    "sd_lbl_fallSleep":"How long did it take you to fall asleep?",
    "sd_lbl_totalAwake":"What was the total time you were awake during sleep?",
    "sd_lbl_getOutBed":"What time did you get out of bed for the day?",
    "sd_lbl_totalSleep":"How long did you sleep?",
    "sd_lbl_sleepQuality":"Rate your quality of sleep:",
    "sd_lbl_sleepEfficiency":"How rested or refreshed did you feel when you woke up for the day?",
    "sd_lbl_totalNap":"How long did you nap or doze yesterday?",
    "sd_lbl_alcohol":"Alcohol: (drink*)",
    "sd_lbl_caffeine":"Caffeine: ( cup of coffee / tea / soda / coke )",
    "sd_lbl_medicine":"Hypnotics: (over-the-counter / prescription medications)",
    "sd_lbl_medication_name":"Name of Medicine:",
    "sd_lbl_dosage":"Dosage:",
    "sd_menu_baReminder":"proACT Notification",
    "sd_baReminder_notSupport":"sd_baReminder_notSupport eng",
    "sd_baReminder_ticker":"proACT Sleep Diary Reminder",
    "sd_baReminder_title":"proACT Sleep Diary Reminder",
    "sd_baReminder_msg":"It's time to fill in the sleep diary!",
    "noConnection_header":"No connection",
    "serverNoConnection_header":"Server Error",
    "serverNoConnection_msg":"Server error, please try again later.",
    "login_locale":"Your location:",
    "login_language":"Language:",
    "hiddenMode":"Please calm down :)"
  },
  "tc":{
    "menuList":[

    ],
    "language":"語言",
    "aboutheader":"關於我們",
    "about":"版權所有 @2012 香港大學心理學系保留所有權利。",
    "disclaimer_0":"注意事項",
    "disclaimer_0_description":"proACT應用程式所提供的資料並不旨在診斷或提供治療，而是協助專業的心理治療師提供心理治療。使用者需承擔自己的風險。proACT應用程式不會收集個人資料。",
    "disclaimer_1":"免責聲明",
    "disclaimer_1_description":"通過使用這個應用程式，表示您同意這些條款及條件。如果您不同意這些使用條款和條件，請不要使用這個應用程式。",
    "disclaimer_11_description":"最後更新：2013年11月18日",
    "disclaimer_111_description":"2012年，香港大學心理學系。保留所有權利。",
    "disclaimer_2":"醫療免責聲明",
    "disclaimer_2_description":"您了解並同意， proACT應用程式所收集的資料可能用作研究用途，並不能依靠作正式的診斷，護理及治療。您通過proACT應用程式所收到的任何資料是不能代替醫療建議及專業判斷 。在依靠proACT 應用程式的資料之前，我們鼓勵您通過可靠的來源以確認proACT 的所有資料。",
    "disclaimer_4":"proACT APP及其授權的責任",
    "disclaimer_4_description":"您承認並同意，您承擔使用proACT應用程式的全部責任，而proACT 應用程式的授權者，供應商或任何在proACT應用程式所提及的第三方不負責任何索賠 。",
    "disclaimer_5":"取消服務",
    "disclaimer_5_description":"您同意我們可能會在任何時間，以任何理由，在沒有警告或補償，取消我們的服務。",
    "disclaimer_6":"修訂",
    "disclaimer_6_description":"我們可能會不時修改本協議。修改協議後，我們可能會，但沒有義務，通知你這些變化，並要求您接受新的協議。",
    "disclaimer_61_description":"不論我們是否已經通知你，如果您繼續使用我們的服務，即表示您接受我們提出的修正案。我們建議您在每次使用proACT應用程式前查閱我們的服務條款。",
    "disclaimer_62_description":"您可能拒絕同意該修訂，但如果你這樣做，你必須立即停止使用我們的服務。",
    "disclaimer_8":"緊急事故",
    "disclaimer_8_description":"由於治療師並不能確保定期閱讀你所提交的紀錄，所以如遇緊急情况，請撥打以下電話號碼：",
    "disclaimer_81_description":"香港警務處 - 電話: 999 (24小時服務熱線)",
    "disclaimer_82_description":"明愛向晴熱線 - 電話: 18288 (24小時服務熱線)",
    "disclaimer_83_description":"生命熱線 - 電話: 23820000 (24小時服務熱線)",
    "disclaimer_84_description":"香港撒瑪利亞防止自殺熱線 - 電話: 23892222 (24小時服務熱線)",
    "disclaimer_85_description":"東華三院芷若園危機介入及支援中心熱線 - 電話: 18281 (24小時服務熱線)",
    "disclaimer_86_description":"香港心理衞生會 心理健康資訊熱線 - 電話: 27720047",
    "disclaimer_87_description":"醫院管理局 精神科熱線 - 電話: 24667350",
    "disclaimer_7":"如中英文版本有差異之處，以英文版本為準。如有任何爭議，香港大學心理學系保留最終決定權。",
    "menu":"目錄",
    "guide":"指南",
    "menu_askLogin":"請先登入!",
    "email":"電郵地址:",
    "password":"密碼:",
    "newPassword":"新密碼:",
    "fname":"名字:",
    "lname":"姓氏:",
    "initial":"姓名簡稱:",
    "refNo":"6 位參考號碼: (如沒有治療師請留空)",
    "therapistlast":"治療師的姓氏:",
    "login":"登入",
    "logout":"登出",
    "logoutError":"登出失敗!",
    "loginError":"錯誤輸入電郵或密碼!",
    "logoutSuccessful":"登出成功!",
    "registration":"註冊",
    "forget":"忘記密碼",
    "register":"註冊",
    "registrationError":"電郵已被註冊!",
    "registrationError1":"沒有此 code!",
    "registrationError2":"此治療師未有於本系統登記!",
    "registrationCodeError":"參考號碼與治療師的姓氏不配合!",
    "registrationFail":"註冊失敗! 請檢查網路連線。",
    "registrationFailF":"註冊失敗!",
    "registrationError_incorrectEmail":"電郵地址格式錯誤!",
    "registrationsSuccessful":"註冊成功!",
    "userInfo":"會員資料",
    "userPassword":"更新密碼",
    "userInfo_update":"更新",
    "userInfo_updateError":"更新失敗!",
    "userInfo_updateSuccessful":"更新成功!",
    "userPassword_updateSuccessful":"更新成功,請重新登入!",
    "back":"返回",
    "next":"下一頁",
    "dtr_situationText":"引起你不愉快的事情:",
    "dtr_initialThoughtText":"最初的想法:",
    "dtr_SummaryBelieveText":"你的想法轉變:",
    "dtr_BelieveText":"閃過你腦海的想法:",
    "dtr_distortionText":"你的扭曲思想:",
    "dtr_modifiedThoughtText":"調整後的反應:",
    "dtr_botheredSituation":"有甚麼事情、想法、思緒或記憶引起不愉快的情緒?",
    "dtr_table_initialThought":"最初的感覺:",
    "dtr_table_modifiedThought":"調整後的感覺:",
    "dtr_table_feeling":"感覺",
    "dtr_table_believe":"信念",
    "dtr_table_initialBelieve":"最初的信念:",
    "dtr_table_modifiedBelieve":"調整後的信念:",
    "dtr_thought":"你怎樣解釋這事情呢？甚麼思想閃過你的腦海?",
    "dtr_emotion":"現在你有甚麼情緒? 這情緒有多強烈 (0-100)?",
    "dtr_anotherSituation":"利用下面列出的問題去構思如何應對即時的想法",
    "dtr_page1":"事件和想法",
    "dtr_page1_feelBar":"這情緒有多強烈 (0-100)?",
    "dtr_page1_feelBar_add":"接此新增情緒‥‥",
    "dtr_page2_feelBar":"你辨認出什麼思想陷阱呢? (可多選)",
    "dtr_page3_feelBar":"這情緒現在有多強烈 (0-100)?",
    "dtr_page2_believeBar":"你當時有多相信這想法 (0-100)?",
    "dtr_page3_believeBar":"你現在有多相信這個即時想法 (0-100)?",
    "dtr_page2":"即時想法",
    "dtr_page3":"調整後的反應",
    "dtr_page4":"總結",
    "dtr_page5":"思想陷阱",
    "dtr_feel":[
      "憤怒 (Angry)",
      "煩擾 (Annoyed)",
      "焦慮 (Anxious)",
      "羞愧 (Ashamed)",
      "悶 (Bored)",
      "迷茫 (Confused)",
      "沮喪 (Dejected)",
      "憂鬱 (Depressed)",
      "士氣低落 (Demoralized)",
      "失望 (Disappointed)",
      "厭惡 (Disgusted)",
      "尷尬 (Embarrassed)",
      "羨慕 (Envious)",
      "害怕 (Frightened)",
      "洩氣 (Frustrated)",
      "內疚 (Guilty)",
      "羞辱 (Humiliated)",
      "受傷害 (Hurt)",
      "不安 (Insecure)",
      "煩 (Irritated)",
      "妒忌 (Jealous)",
      "寂寞 (Lonely)",
      "緊張 (Nervous)",
      "慌張 (Panicky)",
      "怨恨 (Resentful)",
      "傷心 (Sad)",
      "驚慌 (Scared)",
      "不自在 (Self-conscious)",
      "感到大壓力 (Stressed)",
      "憂慮 (Worried)"
    ],
    "dtr_distortion":[
      {
        "name":"全有，全無思維",
        "description":"你對事情的看法只有好與壞兩種。假如你的表現不完美，你就斷定自己完全失敗。"
      },
      {
        "name":"以偏概全",
        "description":"當生活中出現一件不如意的事情，你就斷定你的人生永遠不會如意。"
      },
      {
        "name":"萬般皆黑",
        "description":"你只選擇看事情不好的一面並且老想著這一部分，以致你對所有事的看法都蒙上一層陰影，就好像一滴墨水染黑了整杯水。"
      },
      {
        "name":"否定正面的事實",
        "description":"你否認正面的經驗，並因為某些原因堅持它們「不算數」。你會繼續保持負面的信念，即使這與事實牴觸。"
      },
      {
        "name":"妄下結論",
        "description":"在没有實質證據的支持下，你對事情作出負面的結論。 a. 讀心術﹕你武斷地認定別人對你不好，但不求證。 b. 算命者的謬誤﹕你武斷地認定事情會轉壞，但不求證，而且相信自己的預測已經是既定的事實。"
      },
      {
        "name":"放大 (災難化) 或貶低",
        "description":"你誇大事情的重要性或嚴重性 (例如你一時的粗心或他人的成就)，或者貶低事情的重要性 (例如自己的優點或他人的缺點)。"
      },
      {
        "name":"情緒推理",
        "description":"你假設自己此刻負面的情緒必定反映事實﹕「我覺得係咁，所以事情一定係咁。」"
      },
      {
        "name":"「應該」的陳說",
        "description":"你嘗試用「應該」和「不應該」推動自己，好像你做任何事都需要被鼓舞和懲罰。「一定」和「必需」這些字眼也屬於這一類扭曲，會帶來內疚。當你對他人使用「應該」的用語，你會感到憤怒、挫敗和怨恨。"
      },
      {
        "name":"標籤與錯誤標籤",
        "description":"這是以偏概全的極端。你不客觀地描述自己的過失，為自己貼上負面的標籤﹕「我是一個失敗者。」當他人的行為惹怒了你時，你為他貼上負面的標籤﹕「他是一件垃圾 。」錯誤標籤是指利用帶有偏見和情緒的語言來形容一件事情。"
      },
      {
        "name":"個人化",
        "description":"你將一些負面事件歸咎於自己，盡管事實上你並沒有責任。"
      }
    ],
    "dtr_reference":"參考文獻： Burns, D. D. (1999). The Feeling Good Handbook. Plume.",
    "list":"思想陷阱指南",
    "dtr_page6":"結果",
    "dtr_anotherFeeling":"構思如何應對即時想法（沒有思想陷阱）",
    "dtr_alternativeresponse":"利用下面的問題去幫助你構思另一個反應。",
    "dtr_question_one":"問題 1:",
    "dtr_question_one_step":"有甚麼能證明這即時想法是對或不對﹖",
    "dtr_question_two":"問題 2:",
    "dtr_question_two_step":"有没有另一個解釋﹖",
    "dtr_question_three":"問題 3:",
    "dtr_question_three_step":"最壞的情況會是什麼﹖倘若真的這發生，我可以度過嗎﹖最好的情況會是什麼﹖最真實的結果是什麼﹖",
    "dtr_question_four":"問題 4:",
    "dtr_question_four_step":"若我相信這即時想法，會有什麼影響﹖若我改變我的想法，會有什麼影響﹖",
    "dtr_question_five":"問題 5:",
    "dtr_question_five_step":"我應該如何處理這即時想法﹖",
    "dtr_question_six":"問題 6:",
    "dtr_question_six_step":"如果我的朋友處於這個情況和有這個即時想法，我會向他/她說什麼﹖",
    "dtrMenuList":[

    ],
    "dtr_resultBelieve":"信念的轉變",
    "dtr_resultFeeling":"結果",
    "btnSetting":"設定",
    "dtr_btnRecordJournal":"儲存日記",
    "dtr_btnEmail":"使用電郵發送日記",
    "dtr_btnDelete":"刪除",
    "dtr_btn_email":"發出",
    "dtr_emailSending":"傳送中...",
    "dtr_btn_myEmail":"收件人的電郵",
    "dtr_emailJournalFailure":"失敗!",
    "dtr_emailJournalSuccessful":"成功!",
    "dtr_error_noReceiver":"請輸入收件人的電郵!",
    "dtr_recordJournalFailure":"儲存失敗！原因: 未填寫所有資料。請檢查網路連線和檢查有否填寫所有的欄位。",
    "dtr_deleteJournalFailure":"刪除失敗!",
    "dtr_deleteJournalSuccessful":"刪除成功!",
    "dtr_recordJournalSuccessful":"儲存成功!",
    "dtr_confirmDeleteRecord":"刪除?",
    "dtr_emailReceiver":"收件人:",
    "dtr_header_recordList":"過往的想法日記",
    "therapist":"治療師:",
    "dtrlist_header_guide":"思想陷阱表",
    "dtr_guide_step0_name":"全有，全無思維",
    "dtr_guide_step0_description":"你對事情的看法只有好與壞兩種。假如你的表現不完美，你就斷定自己完全失敗。",
    "dtr_guide_step1_name":"以偏概全",
    "dtr_guide_step1_description":"當生活中出現一件不如意的事情，你就斷定你的人生永遠不會如意。",
    "dtr_guide_step2_name":"萬般皆黑",
    "dtr_guide_step2_description":"你只選擇看事情不好的一面並且老想著這一部分，以致你對所有事的看法都蒙上一層陰影，就好像一滴墨水染黑了整杯水。",
    "dtr_guide_step3_name":"否定正面的事實",
    "dtr_guide_step3_description":"你否認正面的經驗，並因為某些原因堅持它們「不算數」。你會繼續保持負面的信念，即使這與事實牴觸。",
    "dtr_guide_step4_name":"妄下結論",
    "dtr_guide_step4_description":"在没有實質證據的支持下，你對事情作出負面的結論。 a. 讀心術﹕你武斷地認定別人對你不好，但不求證。 b. 算命者的謬誤﹕你武斷地認定事情會轉壞，但不求證，而且相信自己的預測已經是既定的事實。",
    "dtr_guide_step5_name":"放大 (災難化) 或貶低",
    "dtr_guide_step5_description":"你誇大事情的重要性或嚴重性 (例如你一時的粗心或他人的成就)，或者貶低事情的重要性 (例如自己的優點或他人的缺點)。",
    "dtr_guide_step6_name":"情緒推理",
    "dtr_guide_step6_description":"你假設自己此刻負面的情緒必定反映事實﹕「我覺得係咁，所以事情一定係咁。」",
    "dtr_guide_step7_name":"「應該」的陳說",
    "dtr_guide_step7_description":"你嘗試用「應該」和「不應該」推動自己，好像你做任何事都需要被鼓舞和懲罰。「一定」和「必需」這些字眼也屬於這一類扭曲，會帶來內疚。當你對他人使用「應該」的用語，你會感到憤怒、挫敗和怨恨。",
    "dtr_guide_step8_name":"標籤與錯誤標籤",
    "dtr_guide_step8_description":"這是以偏概全的極端。你不客觀地描述自己的過失，為自己貼上負面的標籤﹕「我是一個失敗者。」當他人的行為惹怒了你時，你為他貼上負面的標籤﹕「他是一件垃圾 。」錯誤標籤是指利用帶有偏見和情緒的語言來形容一件事情。",
    "dtr_guide_step9_name":"個人化",
    "dtr_guide_step9_description":"你將一些負面事件歸咎於自己，盡管事實上你並沒有責任。",
    "dtr_guide0_name":"全有，全無思維",
    "dtr_guide1_name":"以偏概全",
    "dtr_guide2_name":"萬般皆黑",
    "dtr_guide3_name":"否定正面的事實",
    "dtr_guide4_name":"妄下結論",
    "dtr_guide5_name":"放大 (災難化) 或貶低",
    "dtr_guide6_name":"情緒推理",
    "dtr_guide7_name":"「應該」的陳說",
    "dtr_guide8_name":"標籤與錯誤標籤",
    "dtr_guide9_name":"個人化",
    "baMenuList":[

    ],
    "mcMenuList":[

    ],
    "mc_header_page1":"情緒表",
    "mc_btn_add":"儲存記錄",
    "mc_lbl_anxious":"你現在感到有多焦慮？(0-100%)",
    "mc_lbl_depressed":"你現在感到有多鬱悶？(0-100%)",
    "mc_lbl_stress":"你現在感到有多少壓力？(0-100%)",
    "mc_header_recordList":"過往已完成的情緒表",
    "mc_lbl_submitDate":"上載日期:",
    "mc_deleteSuccessful":"刪除成功!",
    "mc_recordSuccessful":"儲存成功!",
    "mc_deleteFailure":"刪除失敗!",
    "mc_confirmDeleteRecord":"刪除?",
    "ba_lbl_content":"你完成了甚麼活動？",
    "ba_lbl_anxious":"你現在感到有多焦慮？(0-100%)",
    "ba_lbl_depressed":"你現在感到有多鬱悶？(0-100%)",
    "ba_lbl_stress":"你現在感到有多少壓力？(0-100%)",
    "ba_lbl_date":"日期:",
    "ba_lbl_time":"時間:",
    "ba_lbl_userInputDate":"日期:",
    "ba_lbl_submitDate":"上載日期:",
    "plan_header":"計劃活動",
    "plan_activity":"你計劃做甚麼活動?",
    "plan_time":"你計劃甚麼時候進行此活動?",
    "plan_lbl_date":"日期:",
    "plan_lbl_time":"時間:",
    "plan_btn_add":"儲存計劃",
    "plan_recordFailure":"儲存失敗!請檢查網路連線。",
    "plan_deleteFailure":"刪除失敗!",
    "plan_deleteSuccessful":"刪除成功!",
    "plan_recordSuccessful":"儲存成功!",
    "plan_confirmDeleteRecord":"刪除?",
    "plan_menu_baReminder":"proACT 的提示",
    "plan_baReminder_notSupport":"plan_baReminder_notSupport 中文",
    "plan_baReminder_ticker":"proACT 活動紀錄的提示",
    "plan_baReminder_title":"proACT 活動紀錄的提示",
    "plan_baReminder_msg":"你計劃了實行其中一個活動!",
    "plan_header_recordList":"已建立的計劃",
    "plan_lbl_userInputDate":"日期:",
    "plan_lbl_submitDate":"上載日期:",
    "plan_lbl_activity":"已計劃的活動",
    "ba_btn_add":"儲存記錄",
    "ba_header_page1":"活動",
    "ba_header_page2":"計劃",
    "ba_recordFailure":"儲存失敗！原因: 未填寫所有資料。請檢查網路連線和檢查有否填寫所有的欄位。",
    "ba_deleteFailure":"刪除失敗!",
    "ba_deleteSuccessful":"刪除成功!",
    "ba_recordSuccessful":"儲存成功!",
    "login_lbl_autoLogin":"自動登入",
    "ba_confirmDeleteRecord":"刪除?",
    "ba_header_recordList":"過往已完成的活動",
    "ba_header_recordList2":"已建立的計劃",
    "ba_menu_baReminder":"proACT 的提醒",
    "ba_baReminder_notSupport":"ba_baReminder_notSupport 中文",
    "ba_baReminder_ticker":"proACT 活動記錄的提示",
    "ba_baReminder_title":"proACT 活動記錄的提示",
    "ba_baReminder_msg":"填寫活動記錄的時間到了!",
    "be_lbl_length":"練習時間 (分鐘):",
    "be_lbl_script":"錄音檔:",
    "be_reocrd_lbl_scriptName":"錄音檔名",
    "be_reocrd_btn_start":"開始",
    "be_reocrd_btn_stop":"停止",
    "be_reocrd_msg_pleaseInputName":"請輸入錄音檔名。",
    "be_reocrd_msg_pleaseInputLength":"請輸入練習時間",
    "be_reocrd_msg_pleaseRecord":"請先錄音。",
    "be_reocrd_msg_playRecordError":"找不到錄音檔。",
    "be_reocrd_msg_pleaseStopPlaying":"請先停止播放現在的錄音檔。",
    "be_reocrd_msg_deleteError":"請確定你有把錄音檔儲存並已停止播放。",
    "be_reocrd_msg_deleteConfirmation":"刪除?",
    "be_reocrd_msg_deleteSuccessful":"成功刪除",
    "be_reocrd_msg_deleteFailure":"刪除失敗",
    "be_reocrd_msg_recordFailure":"你的設備不能錄音。",
    "be_reocrd_btn_play":"播放",
    "be_reocrd_btn_pause":"暫停",
    "be_reocrd_btn_delete":"刪除",
    "be_index_btn_record":"錄音",
    "be_index_btn_delete":"刪除",
    "be_index_btn_guide":"指南",
    "be_index_noScript":"沒有選擇任何錄音檔",
    "be_header_index":"放鬆練習",
    "be_header_guide":"放鬆練習指南",
    "be_header_record":"錄音",
    "be_header_delete":"刪除",
    "be_recordFailure":"儲存失敗！請檢查網路連線。",
    "be_recordSuccessful":"儲存成功!",
    "sdMenuList":[

    ],
    "sd_header_index":"睡眠日記",
    "sd_lbl_date":"日期:",
    "sd_goToBed_time":"上床時間:",
    "sd_trySleep_time":"嘗試睡覺的時間:",
    "sd_fallSleep_time":"多久才能入睡:",
    "sd_fallSleep_time_hour":"小時:",
    "sd_fallSleep_time_min":"分鐘:",
    "sd_totalAwake_time":"途中醒來時間總和:",
    "sd_totalAwake_hour":"小時:",
    "sd_totalAwake_min":"分鐘:",
    "sd_getOutBed_time":"離開床時間:",
    "sd_totalSleep_time":"睡眠時間總和:",
    "sd_totalSleep_hour":"小時:",
    "sd_totalSleep_min":"分鐘:",
    "sd_sleepQuality":"睡眠質素的評價:",
    "sd_verygood_sq":"非常好",
    "sd_good_sq":"一般好",
    "sd_poor_sq":"一般差",
    "sd_verypoor_sq":"非常差",
    "sd_sleepEfficiency":"休息充沛程度:",
    "sd_verywell_se":"非常充足",
    "sd_well_se":"很充足",
    "sd_somewhat_se":"頗充足",
    "sd_slightly_se":"稍微充足",
    "sd_notatall_se":"完全不充足",
    "sd_totalNap_time":"昨午小睡時間總和:",
    "sd_totalNap_hour":"小時:",
    "sd_totalNap_min":"分鐘:",
    "sd_alcohol":"酒精: ( 標準值* )",
    "sd_alcoholTxt":"* 1標準值的酒精大概等於1罐標準裝啤酒 或100毫升紅酒 或 25毫升烈酒",
    "sd_caffeine":"咖啡因: ( 杯 咖啡 / 茶 / 汽水 / 可樂 )",
    "sd_medicine":"安眠藥: ( 成藥 / 醫生處方藥物 )",
    "sd_medication_yesTxt":"有",
    "sd_medication_noTxt":"沒有",
    "sd_medication_name":"藥物名稱:",
    "sd_medication_dose":"劑量:",
    "sd_btn_add":"儲存日記",
    "sd_recordSuccessful":"儲存成功!",
    "sd_recordFailure":"記錄失敗！原因: 提交不完整或錯誤輸入'總睡眠時間'(即總睡眠時間多於在床上的總時間)。",
    "sd_deleteSuccessful":"刪除成功!",
    "sd_deleteFailure":"刪除失敗!",
    "sd_confirmDeleteRecord":"刪除?",
    "sd_header_guide":"睡眠日記指南",
    "sd_guide_title":"常見問題 / 指南",
    "sd_guide_step":[
      {
        "name":"1. 上床時間",
        "description":""
      },
      {
        "name":"2. 嘗試睡覺的時間",
        "description":"這可能不是你嘗試入睡的時間。(例如: 晚上 11:00上床, 在床上看書30分鐘, 真正嘗試睡覺的時間是 晚上11:30)"
      },
      {
        "name":"3. 多久才能入睡",
        "description":""
      },
      {
        "name":"4. 途中醒來時間總和",
        "description":"例如: 你醒來3次, 每次20分鐘 (3 X 20分鐘 = 1小時)"
      },
      {
        "name":"5. 離開床時間",
        "description":"離開床並沒有想再嘗試入睡 (例如: 早上8:00醒來, 早上9:00離開床)"
      },
      {
        "name":"6. 睡眠時間總和",
        "description":"\t這是你個人對自己真正睡眠時間的最佳預計"
      },
      {
        "name":"7. 睡眠質素",
        "description":""
      },
      {
        "name":"8. 休息充沛程度",
        "description":"這代表你在醒來後頭幾分鐘感覺睡得怎樣"
      },
      {
        "name":"9. 昨午小睡時間總和",
        "description":"昨天早上起床後到晚上上床之間你小睡/打瞌睡 (恰眼瞓)"
      },
      {
        "name":"10. 酒精: ( 標準值* )",
        "description":"* 1標準值的酒精大概等於1罐標準裝啤酒 或100毫升紅酒 或 25毫升烈酒"
      },
      {
        "name":"11. 咖啡因: ( 杯 咖啡 / 茶 / 汽水 / 可樂 )",
        "description":" 杯 = 以茶餐廳熱飲份量"
      },
      {
        "name":"12. 安眠藥: ( 成藥 / 醫生處方藥物 )",
        "description":"包括醫生處方中西藥, 西成藥及中成藥 ( 有安眠作用 )"
      }
    ],
    "sd_header_recordList":"過往的睡眠日記",
    "sd_lbl_userInputDate":"日期:",
    "sd_lbl_submitDate":"上載日期:",
    "sd_lbl_inbedtime":"上床時間:",
    "sd_lbl_trysleeptime":"嘗試睡覺的時間:",
    "sd_lbl_fallSleep":"多久才能入睡:",
    "sd_lbl_totalAwake":"途中醒來時間總和:",
    "sd_lbl_getOutBed":"離開床時間:",
    "sd_lbl_totalSleep":"睡眠時間總和:",
    "sd_lbl_sleepQuality":"睡眠質素:",
    "sd_lbl_sleepEfficiency":"休息充沛程度:",
    "sd_lbl_totalNap":"昨午小睡時間總和:",
    "sd_lbl_alcohol":"酒精: ( 標準值* )",
    "sd_lbl_caffeine":"咖啡因: ( 杯 咖啡 / 茶 / 汽水 / 可樂 )",
    "sd_lbl_medicine":"安眠藥: ( 成藥 / 醫生處方藥物 )",
    "sd_lbl_medication_name":"藥物名稱:",
    "sd_lbl_dosage":"劑量:",
    "sd_menu_baReminder":"proACT 的提示",
    "sd_baReminder_notSupport":"sd_baReminder_notSupport 中文",
    "sd_baReminder_ticker":"proACT 睡眠日記提示",
    "sd_baReminder_title":"proACT 睡眠日記提示",
    "sd_baReminder_msg":"填寫睡眠日記的時間到了!",
    "noConnection_header":"未能連接網絡",
    "serverNoConnection_header":"伺服器錯誤",
    "serverNoConnection_msg":"未能連接伺服器，請稍後再嘗試。",
    "login_locale":"你的位置:",
    "login_language":"語言:",
    "hiddenMode":":)"
  },
  "sc":{
    "menuList":[

    ],
    "language":"语言",
    "aboutheader":"关于我们",
    "about":"版权所有 @2012 香港大学心理学系保留所有权利。",
    "disclaimer_0":"注意事項",
    "disclaimer_0_description":"proACT应用程式所提供的资料并不旨在诊断或提供治疗，而是协助专业的心理治疗师提供心理治疗。使用者需承担自己的风险。 proACT应用程式不会收集个人资料。",
    "disclaimer_1":"免责声明",
    "disclaimer_1_description":"通过使用这个应用程式，表示您同意这些条款及条件。如果您不同意这些使用条款和条件，请不要使用这个应用程式。",
    "disclaimer_11_description":"最后更新：2013年11月18日",
    "disclaimer_111_description":"2012年，香港大学心理学系。保留所有权利。",
    "disclaimer_2":"医疗免责声明",
    "disclaimer_2_description":"您了解并同意， proACT应用程式所收集的资料可能用作研究用途，并不能依靠作正式的诊断，护理及治疗。您通过proACT应用程式所收到的任何资料是不能代替医疗建议及专业判断。在依靠proACT 应用程式的资料之前，我们鼓励您通过可靠的来源以确认proACT 的所有资料。",
    "disclaimer_4":"proACT APP及其授权的责任",
    "disclaimer_4_description":"您承认并同意，您承担使用proACT应用程式的全部责任，而proACT 应用程式的授权者，供应商或任何在proACT应用程式所提及的第三方不负责任何索赔。",
    "disclaimer_5":"取消服务",
    "disclaimer_5_description":"您同意我们可能会在任何时间，以任何理由，在没有警告或补偿，取消我们的服务。",
    "disclaimer_6":"修订",
    "disclaimer_6_description":"我们可能会不时修改本协议。修改协议后，我们可能会，但没有义务，通知你这些变化，并要求您接受新的协议。",
    "disclaimer_61_description":"不论我们是否已经通知你，如果您继续使用我们的服务，即表示您接受我们提出的修正案。我们建议您在每次使用proACT应用程式前查阅我们的服务条款。",
    "disclaimer_62_description":"您可能拒绝同意该修订，但如果你这样做，你必须立即停止使用我们的服务。",
    "disclaimer_8":"紧急事故",
    "disclaimer_8_description":"由于治疗师并不能确保定期阅读你所提交的纪录，所以如遇紧急情况，请拨打以下电话号码：",
    "disclaimer_81_description":"香港警务处 - 电话: 999 (24小时服务热线)",
    "disclaimer_82_description":"明爱向晴热线 - 电话: 18288 (24小时服务热线)",
    "disclaimer_83_description":"生命热线 - 电话: 23820000 (24小时服务热线)",
    "disclaimer_84_description":"香港撒玛利亚防止自杀热线 - 电话: 23892222 (24小时服务热线)",
    "disclaimer_85_description":"东华三院芷若园危机介入及支援中心热线 - 电话: 18281 (24小时服务热线)",
    "disclaimer_86_description":"香港心理卫生会 心理健康资讯热线 - 电话: 27720047",
    "disclaimer_87_description":"医院管理局 精神科热线 - 电话: 24667350",
    "disclaimer_7":"如中英文版本有差异之处，以英文版本为准。如有任何争议，香港大学心理学系保留最终决定权。",
    "menu":"目录",
    "guide":"指南",
    "menu_askLogin":"请先登入!",
    "email":"电邮地址:",
    "password":"密码:",
    "newPassword":"新密码:",
    "fname":"名字:",
    "lname":"姓氏:",
    "initial":"姓名简称:",
    "refNo":"6 位参考号码: (如沒有治疗师請留空)",
    "therapistlast":"治疗师的姓氏:",
    "login":"登入",
    "logout":"登出",
    "logoutError":"登出失败!",
    "loginError":"错误输入电邮或密码!",
    "logoutSuccessful":"登出成功!",
    "registration":"注册",
    "forget":"忘记密码",
    "register":"注册",
    "registrationError":"电邮已被注册!",
    "registrationError1":"电邮已被注册!",
    "registrationError2":"此治疗师未有于本系统登记!",
    "registrationCodeError":"参考号码与治疗师的姓氏不配合!",
    "registrationFail":"注册失败! 请检查网路连线。",
    "registrationFailF":"注册失败!",
    "registrationError_incorrectEmail":"电邮地址格式错误!",
    "registrationsSuccessful":"注册成功!",
    "userInfo":"会员资料",
    "userPassword":"更新密码",
    "userInfo_update":"更新",
    "userInfo_updateError":"更新失败!",
    "userInfo_updateSuccessful":"更新成功!",
    "userPassword_updateSuccessful":"更新成功,请重新登入!",
    "back":"返回",
    "next":"下一页",
    "dtr_situationText":"引起你不愉快的事情:",
    "dtr_initialThoughtText":"最初的想法:",
    "dtr_SummaryBelieveText":"你的想法转变:",
    "dtr_BelieveText":"闪过你脑海的想法:",
    "dtr_distortionText":"你的扭曲思想:",
    "dtr_modifiedThoughtText":"调整后的反应:",
    "dtr_botheredSituation":"有什么事情、想法、思绪或记忆引起不愉快的情绪?",
    "dtr_table_initialThought":"最初的感觉:",
    "dtr_table_modifiedThought":"调整后的感觉:",
    "dtr_table_feeling":"感觉",
    "dtr_table_believe":"信念",
    "dtr_table_initialBelieve":"最初的信念:",
    "dtr_table_modifiedBelieve":"调整后的信念:",
    "dtr_thought":"你怎样解释这事情呢？什么思想闪过你的脑海?",
    "dtr_emotion":"现在你有什么情绪? 这情绪有多强烈(0-100)?",
    "dtr_anotherSituation":"利用下面列出的问题去构思如何应对即时的想法",
    "dtr_page1":"事件和想法",
    "dtr_page1_feelBar":"这情绪有多强烈(0-100)?",
    "dtr_page1_feelBar_add":"接此新增情绪‥‥",
    "dtr_page2_feelBar":"你辨认出什么思想陷阱呢? (可多选)",
    "dtr_page3_feelBar":"这情绪现在有多强烈(0-100)?",
    "dtr_page2_believeBar":"你当时有多相信这想法(0-100)?",
    "dtr_page3_believeBar":"你现在有多相信这个即时想法(0-100)?",
    "dtr_page2":"即时想法",
    "dtr_page3":"调整后的反应",
    "dtr_page4":"总结",
    "dtr_page5":"思想陷阱",
    "dtr_feel":[
      "愤怒 (Angry)",
      "烦扰 (Annoyed)",
      "焦虑 (Anxious)",
      "羞愧 (Ashamed)",
      "闷 (Bored)",
      "迷茫 (Confused)",
      "沮丧 (Dejected)",
      "忧郁 (Depressed)",
      "士气低落 (Demoralized)",
      "失望 (Disappointed)",
      "厌恶 (Disgusted)",
      "尴尬 (Embarrassed)",
      "羡慕 (Envious)",
      "害怕 (Frightened)",
      "泄气 (Frustrated)",
      "内疚 (Guilty)",
      "羞辱 (Humiliated)",
      "受伤害 (Hurt)",
      "不安 (Insecure)",
      "烦 (Irritated)",
      "妒忌 (Jealous)",
      "寂寞 (Lonely)",
      "紧张 (Nervous)",
      "慌张 (Panicky)",
      "怨恨 (Resentful)",
      "伤心 (Sad)",
      "惊慌 (Scared)",
      "不自在 (Self-conscious)",
      "感到大压力 (Stressed)",
      "忧虑 (Worried)"
    ],
    "dtr_distortion":[
      {
        "name":"全有，全无思维",
        "description":"你对事情的看法只有好与坏两种。假如你的表现不完美，你就断定自己完全失败。"
      },
      {
        "name":"以偏概全",
        "description":"当生活中出现一件不如意的事情，你就断定你的人生永远不会如意。"
      },
      {
        "name":"万般皆黑",
        "description":"你只选择看事情不好的一面并且老想着这一部分，以致你对所有事的看法都蒙上一层阴影，就好像一滴墨水染黑了整杯水。"
      },
      {
        "name":"否定正面的事实",
        "description":"你否认正面的经验，并因为某些原因坚持它们「不算数」。 你会继续保持负面的信念，即使这与事实牴触。 "
      },
      {
        "name":"妄下结论",
        "description":"在没有实质证据的支持下，你对事情作出负面的结论。 a. 读心术﹕你武断地认定别人对你不好，但不求证。 b. 算命者的谬误﹕你武断地认定事情会转坏，但不求证，而且相信自己的预测已经是既定的事实。"
      },
      {
        "name":"放大(灾难化) 或贬低",
        "description":"你夸大事情的重要性或严重性(例如你一时的粗心或他人的成就)，或者贬低事情的重要性(例如自己的优点或他人的缺点)。"
      },
      {
        "name":"情绪推理",
        "description":"你假设自己此刻负面的情绪必定反映事实﹕「我觉得是这样，所以事情一定是这样。」"
      },
      {
        "name":"「应该」的陈说",
        "description":"你尝试用「应该」和「不应该」推动自己，好像你做任何事都需要被鼓舞和惩罚。 「一定」和「必需」这些字眼也属于这一类扭曲，会带来内疚。 当你对他人使用「应该」的用语，你会感到愤怒、挫败和怨恨。 "
      },
      {
        "name":"标签与错误标签",
        "description":"这是以偏概全的极端。你不客观地描述自己的过失，为自己贴上负面的标签﹕「我是一个失败者。」当他人的行为惹怒了你时，你为他贴上负面的标签﹕「他是一件垃圾。」错误标签是指利用带有偏见和情绪的语言来形容一件事情。 "
      },
      {
        "name":"个人化",
        "description":"你将一些负面事件归咎于自己，尽管事实上你并没有责任。"
      }
    ],
    "dtr_reference":"参考文献： Burns, DD (1999). The Feeling Good Handbook. Plume.",
    "list":"思想陷阱指南",
    "dtr_page6":"结果",
    "dtr_anotherFeeling":"构思如何应对即时想法（没有思想陷阱）",
    "dtr_alternativeresponse":"利用下面的问题去帮助你构思另一个反应。",
    "dtr_question_one":"问题1:",
    "dtr_question_one_step":"有什么能证明这即时想法是对或不对﹖",
    "dtr_question_two":"问题2:",
    "dtr_question_two_step":"有没有另一个解释﹖",
    "dtr_question_three":"问题3:",
    "dtr_question_three_step":"最坏的情况会是什么﹖倘若真的这发生，我可以度过吗﹖最好的情况会是什么﹖最真实的结果是什么﹖",
    "dtr_question_four":"问题4:",
    "dtr_question_four_step":"若我相信这即时想法，会有什么影响﹖若我改变我的想法，会有什么影响﹖",
    "dtr_question_five":"问题5:",
    "dtr_question_five_step":"我应该如何处理这即时想法﹖",
    "dtr_question_six":"问题6:",
    "dtr_question_six_step":"如果你的朋友处于这个情况和有这个即时想法，我会向他/她说什么﹖",
    "dtrMenuList":[

    ],
    "dtr_resultBelieve":"信念的转变",
    "dtr_resultFeeling":"结果",
    "btnSetting":"设定",
    "dtr_btnRecordJournal":"储存日记",
    "dtr_btnEmail":"使用电邮发送日记",
    "dtr_btnDelete":"删除",
    "dtr_btn_email":"发出",
    "dtr_emailSending":"传送中...",
    "dtr_btn_myEmail":"收件人的电邮",
    "dtr_emailJournalFailure":"失败!",
    "dtr_emailJournalSuccessful":"成功!",
    "dtr_error_noReceiver":"请输入收件人的电邮!",
    "dtr_recordJournalFailure":"储存失败！原因: 未填写所有资料。请检查网路连线和检查有否填写所有的栏位。",
    "dtr_deleteJournalFailure":"删除失败!",
    "dtr_deleteJournalSuccessful":"删除成功!",
    "dtr_recordJournalSuccessful":"储存成功!",
    "dtr_confirmDeleteRecord":"删除?",
    "dtr_emailReceiver":"收件人:",
    "dtr_header_recordList":"过往的想法日记",
    "therapist":"治疗师:",
    "dtrlist_header_guide":"思想陷阱表",
    "dtr_guide_step0_name":"全有，全无思维",
    "dtr_guide_step0_description":"你对事情的看法只有好与坏两种。假如你的表现不完美，你就断定自己完全失败。",
    "dtr_guide_step1_name":"以偏概全",
    "dtr_guide_step1_description":"当生活中出现一件不如意的事情，你就断定你的人生永远不会如意。",
    "dtr_guide_step2_name":"万般皆黑",
    "dtr_guide_step2_description":"你只选择看事情不好的一面并且老想着这一部分，以致你对所有事的看法都蒙上一层阴影，就好像一滴墨水染黑了整杯水。 ",
    "dtr_guide_step3_name":"否定正面的事实",
    "dtr_guide_step3_description":"你否认正面的经验，并因为某些原因坚持它们「不算数」。 你会继续保持负面的信念，即使这与事实牴触。 ",
    "dtr_guide_step4_name":"妄下结论",
    "dtr_guide_step4_description":"在没有实质证据的支持下，你对事情作出负面的结论。 a. 读心术﹕你武断地认定别人对你不好，但不求证。 b. 算命者的谬误﹕你武断地认定事情会转坏，但不求证，而且相信自己的预测已经是既定的事实。",
    "dtr_guide_step5_name":"放大(灾难化) 或贬低",
    "dtr_guide_step5_description":"你夸大事情的重要性或严重性(例如你一时的粗心或他人的成就)，或者贬低事情的重要性(例如自己的优点或他人的缺点)。",
    "dtr_guide_step6_name":"情绪推理",
    "dtr_guide_step6_description":"你假设自己此刻负面的情绪必定反映事实﹕「我觉得是这样，所以事情一定是这样。」",
    "dtr_guide_step7_name":"「应该」的陈说",
    "dtr_guide_step7_description":"你尝试用「应该」和「不应该」推动自己，好像你做任何事都需要被鼓舞和惩罚。 「一定」和「必需」这些字眼也属于这一类扭曲，会带来内疚。 当你对他人使用「应该」的用语，你会感到愤怒、挫败和怨恨。 ",
    "dtr_guide_step8_name":"标签与错误标签",
    "dtr_guide_step8_description":"这是以偏概全的极端。你不客观地描述自己的过失，为自己贴上负面的标签﹕「我是一个失败者。」当他人的行为惹怒了你时，你为他贴上负面的标签﹕「他是一件垃圾。」错误标签是指利用带有偏见和情绪的语言来形容一件事情。 ",
    "dtr_guide_step9_name":"个人化",
    "dtr_guide_step9_description":"你将一些负面事件归咎于自己，尽管事实上你并没有责任。",
    "dtr_guide0_name":"全有，全无思维",
    "dtr_guide1_name":"以偏概全",
    "dtr_guide2_name":"万般皆黑",
    "dtr_guide3_name":"否定正面的事实",
    "dtr_guide4_name":"妄下结论",
    "dtr_guide5_name":"放大(灾难化) 或贬低",
    "dtr_guide6_name":"情绪推理",
    "dtr_guide7_name":"「应该」的陈说",
    "dtr_guide8_name":"标签与错误标签",
    "dtr_guide9_name":"个人化",
    "baMenuList":[

    ],
    "mcMenuList":[

    ],
    "mc_header_page1":"情绪表",
    "mc_btn_add":"储存记录",
    "mc_lbl_anxious":"你现在感到有多焦虑？(0-100%)",
    "mc_lbl_depressed":"你现在感到有多郁闷？(0-100%)",
    "mc_lbl_stress":"你现在感到有多少压力？(0-100%)",
    "mc_header_recordList":"过往已完成的情緒表",
    "mc_lbl_submitDate":"上载日期:",
    "mc_deleteSuccessful":"删除成功!",
    "mc_recordSuccessful":"储存成功!",
    "mc_deleteFailure":"删除失败!",
    "mc_confirmDeleteRecord":"删除?",
    "ba_lbl_content":"你完成了什么活动？",
    "ba_lbl_anxious":"你现在感到有多焦虑？(0-100%)",
    "ba_lbl_depressed":"你现在感到有多郁闷？(0-100%)",
    "ba_lbl_stress":"你现在感到有多少压力？(0-100%)",
    "ba_lbl_date":"日期:",
    "ba_lbl_time":"时间:",
    "ba_lbl_userInputDate":"日期:",
    "ba_lbl_submitDate":"上载日期:",
    "plan_header":"计划活动",
    "plan_activity":"你计划做什么活动?",
    "plan_time":"你计划什么时候进行此活动?",
    "plan_lbl_date":"日期:",
    "plan_lbl_time":"时间:",
    "plan_btn_add":"储存计划",
    "plan_recordFailure":"储存失败!请检查网路连线。",
    "plan_deleteFailure":"删除失败!",
    "plan_deleteSuccessful":"删除成功!",
    "plan_recordSuccessful":"储存成功!",
    "plan_confirmDeleteRecord":"删除?",
    "plan_menu_baReminder":"proACT 的提示",
    "plan_baReminder_notSupport":"plan_baReminder_notSupport 中文",
    "plan_baReminder_ticker":"proACT 活动纪录的提示",
    "plan_baReminder_title":"proACT 活动纪录的提示",
    "plan_baReminder_msg":"你计划了实行其中一个活动!",
    "plan_header_recordList":"已建立的计划",
    "plan_lbl_userInputDate":"日期:",
    "plan_lbl_submitDate":"上载日期:",
    "plan_lbl_activity":"已计划的活动",
    "ba_btn_add":"储存记录",
    "ba_header_page1":"活动",
    "ba_header_page2":"计划",
    "ba_recordFailure":"储存失败！原因: 未填写所有资料。请检查网路连线和检查有否填写所有的栏位。",
    "ba_deleteFailure":"删除失败!",
    "ba_deleteSuccessful":"删除成功!",
    "ba_recordSuccessful":"储存成功!",
    "login_lbl_autoLogin":"自动登入",
    "ba_confirmDeleteRecord":"删除?",
    "ba_header_recordList":"过往已完成的活动",
    "ba_header_recordList2":"已建立的计划",
    "ba_menu_baReminder":"proACT 的提示",
    "ba_baReminder_notSupport":"ba_baReminder_notSupport 中文",
    "ba_baReminder_ticker":"proACT 活动记录的提示",
    "ba_baReminder_title":"proACT 活动记录的提示",
    "ba_baReminder_msg":"填写活动记录的时间到了!",
    "be_lbl_length":"练习时间 (分钟):",
    "be_lbl_script":"录音档:",
    "be_reocrd_lbl_scriptName":"录音档名",
    "be_reocrd_btn_start":"开始",
    "be_reocrd_btn_stop":"停止",
    "be_reocrd_msg_pleaseInputName":"请输入录音档名。",
    "be_reocrd_msg_pleaseInputLength":"请输入练习时间",
    "be_reocrd_msg_pleaseRecord":"请先录音。",
    "be_reocrd_msg_playRecordError":"找不到录音档。",
    "be_reocrd_msg_pleaseStopPlaying":"请先停止播放现在的录音档。",
    "be_reocrd_msg_deleteError":"请确定你有把录音档储存并已停止播放。",
    "be_reocrd_msg_deleteConfirmation":"删除?",
    "be_reocrd_msg_deleteSuccessful":"成功删除",
    "be_reocrd_msg_deleteFailure":"删除失败",
    "be_reocrd_msg_recordFailure":"你的设备不能录音。",
    "be_reocrd_btn_play":"播放",
    "be_reocrd_btn_pause":"暂停",
    "be_reocrd_btn_delete":"删除",
    "be_index_btn_record":"录音",
    "be_index_btn_delete":"删除",
    "be_index_btn_guide":"指南",
    "be_index_noScript":"没有选择任何录音档",
    "be_header_index":"放松练习",
    "be_header_guide":"放松练习指南",
    "be_header_record":"录音",
    "be_header_delete":"删除",
    "be_recordFailure":"储存失败！请检查网路连线。",
    "be_recordSuccessful":"储存成功!",
    "sdMenuList":[

    ],
    "sd_header_index":"睡眠日记",
    "sd_lbl_date":"日期:",
    "sd_goToBed_time":"上床时间:",
    "sd_trySleep_time":"尝试睡觉的时间:",
    "sd_fallSleep_time":"多久才能入睡:",
    "sd_fallSleep_time_hour":"小时:",
    "sd_fallSleep_time_min":"分钟:",
    "sd_totalAwake_time":"途中醒来时间总和:",
    "sd_totalAwake_hour":"小时:",
    "sd_totalAwake_min":"分钟:",
    "sd_getOutBed_time":"离开床的时间:",
    "sd_totalSleep_time":"睡眠时间总和:",
    "sd_totalSleep_hour":"小时:",
    "sd_totalSleep_min":"分钟:",
    "sd_sleepQuality":"睡眠质素的评价:",
    "sd_verygood_sq":"非常好",
    "sd_good_sq":"一般好",
    "sd_poor_sq":"一般差",
    "sd_verypoor_sq":"非常差",
    "sd_sleepEfficiency":"休息充沛程度:",
    "sd_verywell_se":"非常充足",
    "sd_well_se":"很充足",
    "sd_somewhat_se":"颇充足",
    "sd_slightly_se":"稍微充足",
    "sd_notatall_se":"完全不充足",
    "sd_totalNap_time":"昨午小睡时间总和:",
    "sd_totalNap_hour":"小时:",
    "sd_totalNap_min":"分钟:",
    "sd_alcohol":"酒精: ( 标准值* )",
    "sd_alcoholTxt":"* 1标准值的酒精大概等于1罐标准装啤酒或100毫升红酒或25毫升烈酒",
    "sd_caffeine":"咖啡因: ( 杯咖啡 / 茶 / 汽水 / 可乐 )",
    "sd_medicine":"安眠药: ( 成药 / 医生处方药物 )",
    "sd_medication_yesTxt":"有",
    "sd_medication_noTxt":"没有",
    "sd_medication_name":"药物名称:",
    "sd_medication_dose":"剂量:",
    "sd_btn_add":"储存日记",
    "sd_recordSuccessful":"储存成功!",
    "sd_recordFailure":"记录失败！原因: 提交不完整或错误输入'总睡眠时间'(即总睡眠时间多于在床上的总时间)。",
    "sd_deleteSuccessful":"删除成功!",
    "sd_deleteFailure":"删除失败!",
    "sd_confirmDeleteRecord":"删除?",
    "sd_header_guide":"睡眠日记指南",
    "sd_guide_title":"常见问题/ 指南",
    "sd_guide_step":[
      {
        "name":"1. 上床时间",
        "description":""
      },
      {
        "name":"2. 尝试睡觉的时间",
        "description":"這可能不是你上床的时间。(例如: 晚上11:00上床, 在床上看书30分钟, 真正尝试睡觉的时间是晚上11:30)"
      },
      {
        "name":"3. 多久才能入睡",
        "description":""
      },
      {
        "name":"4. 途中醒来的时间总和",
        "description":"例如: 你醒来3次, 每次20分钟(3 X 20分钟= 1小时)"
      },
      {
        "name":"5. 离开床的时间",
        "description":"离开床并没有想再尝试入睡(例如: 早上8:00醒来, 早上9:00离开床)"
      },
      {
        "name":"6. 睡眠时间总和",
        "description":" 这是你个人对自己真正睡眠时间的最佳预计"
      },
      {
        "name":"7. 睡眠质素",
        "description":""
      },
      {
        "name":"8. 休息充沛程度",
        "description":"这代表你在醒来后头几分钟感觉睡得怎样"
      },
      {
        "name":"9. 昨午小睡时间总和",
        "description":"昨天早上起床后到晚上上床之间你小睡/打瞌睡"
      },
      {
        "name":"10. 酒精: ( 标准值* )",
        "description":"* 1标准值的酒精大概等于1罐标准装啤酒或100毫升红酒或25毫升烈酒"
      },
      {
        "name":"11. 咖啡因: ( 杯咖啡 / 茶 / 汽水 / 可乐 )",
        "description":" 杯= 以茶餐厅热饮份量"
      },
      {
        "name":"12. 安眠药: ( 成药 / 医生处方药物 )",
        "description":"包括医生处方中西药, 西成药及中成药 ( 有安眠作用 )"
      }
    ],
    "sd_header_recordList":"过往的睡眠日记",
    "sd_lbl_userInputDate":"日期:",
    "sd_lbl_submitDate":"上载日期:",
    "sd_lbl_inbedtime":"上床时间:",
    "sd_lbl_trysleeptime":"尝试睡觉的时间:",
    "sd_lbl_fallSleep":"多久才能入睡:",
    "sd_lbl_totalAwake":"途中醒来的时间总和:",
    "sd_lbl_getOutBed":"离开床的时间:",
    "sd_lbl_totalSleep":"睡眠时间总和:",
    "sd_lbl_sleepQuality":"睡眠质素:",
    "sd_lbl_sleepEfficiency":"休息充沛程度:",
    "sd_lbl_totalNap":"昨午小睡的时间总和:",
    "sd_lbl_alcohol":"酒精: ( 标准值* )",
    "sd_lbl_caffeine":"咖啡因: ( 杯咖啡 / 茶 / 汽水 / 可乐 )",
    "sd_lbl_medicine":"安眠药: ( 成药 / 医生处方药物 )",
    "sd_lbl_medication_name":"药物名称:",
    "sd_lbl_dosage":"剂量:",
    "sd_menu_baReminder":"proACT 的提示",
    "sd_baReminder_notSupport":"sd_baReminder_notSupport 中文",
    "sd_baReminder_ticker":"proACT 睡眠日记提示",
    "sd_baReminder_title":"proACT 睡眠日记提示",
    "sd_baReminder_msg":"填写睡眠日记的时间到了!",
    "noConnection_header":"未能连接网络",
    "serverNoConnection_header":"服务器错误",
    "serverNoConnection_msg":"未能连接服务器，请稍后再尝试。",
    "login_locale":"你的位置:",
    "login_language":"语言:",
    "hiddenMode":":)"
  }
}
